"""Add feedback column to code_analyses

Revision ID: a7648d3ed81a
Revises: 7e788e7b606b
Create Date: 2025-05-04 00:26:04.628935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7648d3ed81a'
down_revision: Union[str, None] = '7e788e7b606b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_analyses', sa.Column('feedback', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_analyses', 'feedback')
    # ### end Alembic commands ###
